# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
# CC0 1.0 Universal

environment:

  matrix:

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x"
      TOX_ENV: "py34-tests"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      TOX_ENV: "py35-tests"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      TOX_ENV: "py36-tests"

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"

  - "pip install tox"

build: off

test_script:
  # Run the project tests
  - "tox -e %TOX_ENV%"

after_test:
 - pip install codecov
 - "codecov -f coverage.xml -t %CODECOV_TOKEN%"
