pep257:
  disable:
    - D105  # Missing docstring in magic method
    - D200  # One-line docstring should fit on one line with quotes
    - D203  # 1 blank line required before class docstring
    - D204  # 1 blank line required after class docstring
    - D205  # 1 blank line required between summary line and description
    - D212  # Multi-line docstring summary should start at the first line

pylint:
  disable:
    - logging-format-interpolation  # Use % formatting in logging functions and pass the % parameters as arguments
    - too-many-arguments  # Too many arguments
